import { signIn, signOut, useSession } from "next-auth/react";
import Icon from "@/components/Icon";
import Head from "next/head";
import Avatar from "@/components/Avatar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-32 flex gap-2">
        <Avatar variant="initials" name="Cosmin" />
        <Avatar
          variant="image"
          avatar="https://i.pravatar.cc/150?u=a042581f4e29026024d"
        />
        <Avatar
          variant="image"
          avatar="https://i.pravatar.cc/150?u=a042581f4e29026024d"
          indicator="check"
        />
        <Avatar
          variant="image"
          avatar="https://i.pravatar.cc/150?u=a042581f4e29026024d"
          indicator="minus"
        />
        <Avatar
          variant="image"
          avatar="https://i.pravatar.cc/150?u=a042581f4e29026024d"
          indicator="question"
        />
        <Avatar variant="icon" iconId="eyeClosed" />
        <Avatar
          variant="image"
          avatar="https://i.pravatar.cc/150?u=a042581f4e29026024d"
          santaHat
        />
      </main>

      <AuthShowcase />
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
