import { signIn, signOut, useSession } from "next-auth/react";
import Icon from "@/components/Icon";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Icon iconId="calendar" />
        <Icon iconId="check" />
        <Icon iconId="chevron" />
        <Icon iconId="close" />
        <Icon iconId="eyeClosed" />
        <Icon iconId="eyeOpened" />
        <Icon iconId="logout" />
        <Icon iconId="minus" />
        <Icon iconId="plus" />
        <Icon iconId="question" />
        <Icon iconId="thumbsDown" />
        <Icon iconId="thumbsUp" />
        <Icon iconId="upload" />
        <Icon iconId="user" />
      </main>

      <AuthShowcase />
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();
  console.log(sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
